namespace :slc_model_groups do
  # bundle exec rake slc_model_groups:import
   desc "Import SLC Model groups"
   task import: :environment do 
     rows = Roo::Spreadsheet.open('db/SLC_Model_group.xlsx', extension: :xlsx)
     rows.each do |row|
      make = Make.where("LOWER(name) = ?", row[0]&.downcase).first
      if make.present?
        SlcModelGroup.find_or_create_by(
            make_id:  make.id,
            model_year: row[2],
            model: row[4],
            slc_model_group_name: row[3]
          )  
      else
        puts "Make : #{row[0]} not found"
      end
    end
  end

  desc "Add missing 2019 SLC Model Group"
  task add_2019_xg500_street: :environment do
    SlcModelGroup.create(model_year: "2019", model: "XG500 Street", slc_model_group_name: "Street", make_id: 1)
  end  

  desc "Add missing 2020 SLC Model Groups"
  task seed_2020_records: :environment do
    SlcModelGroup.create(model_year: "2020", model: "Challenger", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Challenger Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Challenger Dark Horse Smoke", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chief Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chief Vintage (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chief Vintage (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chief Vintage Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chief Vintage Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Classic (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Classic (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Classic Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Classic Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Dark Horse (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Dark Horse Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Elite", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Limited", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Limited (Radar Blue)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Limited (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Limited (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Chieftain Limited Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "FLDE Deluxe", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLFB Fat Boy", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLFBS Fat Boy 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLFBSANV Fat Boy 114 Anniversary", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHC Heritage Classic", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHCS Heritage Classic 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHP Police Road King", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHR Road King", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHRXS Road King Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHT Electra Glide Standard", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTCU Electra Glide Ultra Classic", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTCUTG Tri Glide Ultra", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTCUTG Tri Glide Ultra (Vivid Black)", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTCUTGSE CVO Tri Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTK Ultra Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTK Ultra Limited Custom", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTKL Ultra Limited Low", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTKSE CVO Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHTP Police Electra Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHX Street Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHXS Street Glide Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLHXSE CVO Street Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLRT Freewheeler", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLSB Sport Glide", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLSL Softail Slim", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRK Road Glide Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRK Road Glide Limited Custom", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRU Road Glide Ultra", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRX Road Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRXS Road Glide Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FLTRXSE CVO Road Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FTR 1200", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "FTR 1200 S", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "FTR 1200 S Race Replica", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "FXBB Street Bob", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXBR Breakout", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXBRS Breakout 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXDRS FXDR 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXFB Fat Bob", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXFBS Fat Bob 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXLR Low Rider", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXLRS Low Rider S", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "FXST Softail Standard", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster (Burgundy Metallic)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster (Pearl White Metallic)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Elite", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Icon (Dirt Track Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Icon (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Roadmaster Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout (ABS, Two Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout (ABS, Two-Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout 100th Anniversary", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber Icon (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber Twenty", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber Twenty ABS", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bobber Twenty ABS (Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Bober Icon (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Icon (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Icon (ABS, Two Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty  (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty (ABS, Two-Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty (Thunder Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty ABS (Burgundy Metallic)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Scout Sixty ABS (Pearl White Metallic)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Springfield (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Springfield (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Springfield Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Springfield Dark Horse (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "Springfield Dark Horse (White Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2020", model: "XG500 Street", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XG750 Street", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XG750A Street Rod", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL1200 Iron 1200", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL1200C Custom", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL1200CX Roadster", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL1200X Forty-Eight", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL1200XS Forty-Eight Special", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL883L Superlow", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2020", model: "XL883N Iron 883", slc_model_group_name: "Sportster", make_id: 1)
  end

  desc "Add eight new model years"
  task add_eight_model_years: :environment do
    SlcModelGroup.create(model_year: "2012", model: "XL1200V Seventy-Two (Denim/Pearl)", slc_model_group_name: "Cruisers", make_id: 1)
    SlcModelGroup.create(model_year: "2015", model: "FLHTCUL Ultra Classic Electra Glide Low", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2017", model: "FLHTK Ultra Limited Low", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2018", model: "FLHX Street Glide Hard Candy", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2018", model: "FLHXS Street Glide Special Hard Candy", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2018", model: "FLTRX Road Glide Hard Candy", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2018", model: "FLTRXS Road Glide Special Hard Candy", slc_model_group_name: "Touring", make_id: 1)    
    SlcModelGroup.create(model_year: "2019", model: "FLHT Electra Glide Standard", slc_model_group_name: "Touring", make_id: 1)
  end

  desc "Add missing 2021 SLC Model Groups"
  task seed_2021_records: :environment do
    SlcModelGroup.create(model_year: "2021", model: "Challenger", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger Dark Horse Smoke", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chief Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chief Vintage (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chief Vintage (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chief Vintage Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chief Vintage Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Classic (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Classic (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Classic Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Classic Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Dark Horse (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Dark Horse Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Elite", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited (Radar Blue)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "FLDE Deluxe", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLFB Fat Boy", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLFBS Fat Boy 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLFBSANV Fat Boy 114 Anniversary", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHC Heritage Classic", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHCS Heritage Classic 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHP Police Road King", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHR Road King", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHRXS Road King Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHT Electra Glide Standard", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTCU Electra Glide Ultra Classic", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTCUTG Tri Glide Ultra", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTCUTG Tri Glide Ultra (Vivid Black)", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTCUTGSE CVO Tri Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTK Ultra Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTK Ultra Limited Custom", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTKL Ultra Limited Low", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTKSE CVO Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTP Police Electra Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHX Street Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHXS Street Glide Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHXSE CVO Street Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLRT Freewheeler", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLSB Sport Glide", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLSL Softail Slim", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRK Road Glide Limited", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRK Road Glide Limited Custom", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRU Road Glide Ultra", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRX Road Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRXS Road Glide Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLTRXSE CVO Road Glide", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FTR 1200", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "FTR 1200 S", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "FTR 1200 S Race Replica", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "FXBB Street Bob", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXBR Breakout", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXFB Fat Bob", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXFBS Fat Bob 114", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXLR Low Rider", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXLRS Low Rider S", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXST Softail Standard", slc_model_group_name: "Softail", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Burgundy Metallic)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Pearl White Metallic)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Elite", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Icon", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Icon (Dirt Track Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Icon (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Icon (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout (ABS, Two Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout (ABS, Two-Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout 100th Anniversary", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Icon (ABS, Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Twenty", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Twenty ABS", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Twenty ABS (Color)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bober Icon (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Icon (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Icon (ABS, Two Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty  (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty (ABS, Two-Tone)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty (Thunder Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty ABS (Burgundy Metallic)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty ABS (Pearl White Metallic)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield Dark Horse (Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield Dark Horse (Thunder Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield Dark Horse (White Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "XG500 Street", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XG750 Street", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XG750A Street Rod", slc_model_group_name: "Street", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200 Iron 1200", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200C Custom", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200CX Roadster", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200X Forty-Eight", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200XS Forty-Eight Special", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL883L Superlow", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL883N Iron 883", slc_model_group_name: "Sportster", make_id: 1)
  end

  desc "Add new 2021 Indian models"
  task add_2021_new_indian_models: :environment do
    SlcModelGroup.create(model_year: "2021", model: "Challenger (Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger (Metallic Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger Dark Horse (Black Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger Limited", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Challenger Limited (Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Dark Horse (Black Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited (Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Chieftain Limited (Blue)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster (Black)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Dark Horse (Black Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster JD LE", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Roadmaster Limited", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobbber Sixty (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber (ABS, Black Smoke)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber (ABS, Smoke)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber ICON (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Sixty", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Sixty (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Twenty (ABS)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Bobber Twenty (ABS, Black Smoke)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty (ABS, Black)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Scout Sixty (ABS, Ruby)", slc_model_group_name: "Scout", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield Dark Horse", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Springfield Dark Horse (Black Smoke)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Vintage (Crimson Metallic)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Vintage (Two-Tone)", slc_model_group_name: "Chief", make_id: 94)
    SlcModelGroup.create(model_year: "2021", model: "Vintage Dark Horse", slc_model_group_name: "Chief", make_id: 94)
  end

  desc "Add new 2021 Harley models"
  task add_2021_new_harley_models: :environment do
    SlcModelGroup.create(model_year: "2021", model: "XL883N Iron 833", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "XL1200NS Iron 1200", slc_model_group_name: "Sportster", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FKTRXS Road Glide Special", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTCUTG Tri Glide Ultra Classic", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FLHTK Electra Glide Ultra Limited Shrine", slc_model_group_name: "Touring", make_id: 1)
    SlcModelGroup.create(model_year: "2021", model: "FXBBS Street Bob 114", slc_model_group_name: "Softail", make_id: 1)
  end

end