namespace :update_cities_167494910 do
  desc 'Update Cities'
  task update: :environment do
    cities.each do |city|
      if City.exists?(city[:id])
        City.find(city[:id]).update_column(:name, city[:name])
      end
    end
  end
  
  def cities
    [
      { id: 892, name:	"GILA RIVER INDIAN RESERV"},
      { id: 904, name:	"KAIBAB INDIAN RESERVATIO"},
      { id: 905, name:	"KAIBAB-PAIUTE INDIAN RES"},
      { id: 921, name:	"PETRIFIED FOREST NATIONA"},
      { id: 930, name:	"SAN CARLOS INDIAN RESERV"},
      { id: 938, name:	"TOHONO O'ODHAM INDIAN RE"},
      { id: 941, name:	"YAVAPAI APACHE INDIAN RE"},
      { id: 956, name:	"COCOPAH INDIAN RESERVATI"},
      { id: 957, name:	"COLORADO RIVER INDIAN RE"},
      { id: 968, name:	"FORT MCDOWELL INDIAN RES"},
      { id: 969, name:	"FORT MCDOWELL-YAVAPAI IN"},
      { id: 972, name:	"GILA RIVER INDIAN RESERV"},
      { id: 973, name:	"GILA RIVER INDIAN RESERV"},
      { id: 974, name:	"GILA RIVER INDIAN RESERV"},
      { id: 986, name:	"HUALAPAI INDIAN RESERVAT"},
      { id: 990, name:	"KAIBAB INDIAN RESERVATIO"},
      { id: 991, name:	"KAIBAB-PAIUTE INDIAN RES"},
      { id: 1002, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 1003, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 1038, name:	"SAN CARLOS INDIAN RESERV"},
      { id: 1052, name:	"TOHONO O'ODHAM INDIAN RE"},
      { id: 1067, name:	"YAVAPAI-PRESCOTT INDIAN"},
      { id: 1097, name:	"FORT MCDOWELL INDIAN RES"},
      { id: 1098, name:	"FORT MCDOWELL-YAVAPAI IN"},
      { id: 1103, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1104, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1105, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1117, name:	"HUALAPAI INDIAN RESERVAT"},
      { id: 1118, name:	"HUALAPAI INDIAN RESERVAT"},
      { id: 1133, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 1155, name:	"SAN CARLOS INDIAN RESERV"},
      { id: 1175, name:	"TOHONO O'ODHAM INDIAN RE"},
      { id: 1176, name:	"TOHONO O'ODHAM INDIAN RE"},
      { id: 1246, name:	"FORT MOJAVE INDIAN RESER"},
      { id: 1248, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1249, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1250, name:	"GILA RIVER INDIAN RESERV"},
      { id: 1259, name:	"HUALAPAI INDIAN RESERVAT"},
      { id: 1260, name:	"HUALAPAI INDIAN RESERVAT"},
      { id: 1301, name:	"SALT RIVER INDIAN RESERV"},
      { id: 1303, name:	"SAN JUAN SOUTH PAUITE IN"},
      { id: 1333, name:	"WHITE MOUNTAIN APACHE IN"},
      { id: 1334, name:	"WHITE MOUNTAIN APACHE IN"},
      { id: 1335, name:	"WHITE MOUNTAIN APACHE IN"},
      { id: 1694, name:	"HOT SPRINGS NATIONAL PAR"},
      { id: 1695, name:	"HOT SPRINGS NATIONAL PAR"},
      { id: 1710, name:	"LITTLE ROCK AIR FORCE BA"},
      { id: 1711, name:	"LITTLE ROCK AIR FORCE BA"},
      { id: 2067, name:	"HOT SPRINGS NATIONAL PAR"},
      { id: 3780, name:	"KINGS CANYON NATIONAL PA"},
      { id: 4113, name:	"TULE RIVER INDIAN RESERV"},
      { id: 4856, name:	"MOUNT CRESTED BUTTE TOWN"},
      { id: 5037, name:	"MASHANTUCKET PEQUOT INDI"},
      { id: 5470, name:	"AEROPOST INTERNATIONAL S"},
      { id: 5776, name:	"ISLAMORADA-VILLAGE OF IS"},
      { id: 6069, name:	"ISLAMORADA-VILLAGE OF IS"},
      { id: 6986, name:	"WEBSTER COUNTY UNIFIED G"},
      { id: 7629, name:	"WEBSTER COUNTY UNIFIED G"},
      { id: 7653, name:	"JOINT BASE PEARL HARBOR-"},
      { id: 7717, name:	"JOINT BASE PEARL HARBOR-"},
      { id: 7742, name:	"TRIPLER ARMY MEDICAL CEN"},
      { id: 10928, name:	"CAMP DODGE MILITARY RESE"},
      { id: 12896, name:	"ST. MARYS"},
      { id: 12897, name:	"ST. MARYS"},
      { id: 14306, name:	"NEW ORLEANS INTERNATIONA"},
      { id: 15281, name:	"CHEVY CHASE SECTION THRE"},
      { id: 15449, name:	"SAINT MARYS CITY"},
      { id: 15463, name:	"ST MARYS CITY"},
      { id: 15912, name:	"FRAMINGHAM CENTER"},
      { id: 16041, name:	"PADANARAM VILLAGE"},
      { id: 16070, name:	"S YARMOUTH"},
      { id: 16162, name:	"WEST DIGHTON"},
      { id: 16290, name:	"VETERANS ADMINISTRATION"},
      { id: 16326, name:	"DARTHMOUTH"},
      { id: 17750, name:	"WHITE EARTH INDIAN RESER"},
      { id: 17751, name:	"WHITE EARTH INDIAN RESER"},
      { id: 17775, name:	"BOIS FORTE INDIAN RESERV"},
      { id: 17776, name:	"BOIS FORTE INDIAN RESERV"},
      { id: 17816, name:	"GRAND PORTAGE INDIAN RES"},
      { id: 17854, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 17855, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 17856, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 17857, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 17865, name:	"LOWER SIOUX INDIAN RESER"},
      { id: 17894, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17895, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17896, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17897, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17898, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17899, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17900, name:	"RED LAKE BAND INDIAN RES"},
      { id: 17934, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18004, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18005, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18045, name:	"PRAIRIE ISLAND SIOUX IND"},
      { id: 18175, name:	"SHAKOPEE MDEWAKANTON SIO"},
      { id: 18224, name:	"BOIS FORTE INDIAN RESERV"},
      { id: 18225, name:	"BOIS FORTE INDIAN RESERV"},
      { id: 18226, name:	"BOIS FORTE INDIAN RESERV"},
      { id: 18333, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18334, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18335, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18336, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18337, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18338, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18445, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18446, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18447, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18448, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18449, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18450, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18451, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18452, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18453, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18454, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18455, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18456, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18457, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18458, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18491, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18492, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18493, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18494, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18495, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18496, name:	"MILLE LACS INDIAN RESERV"},
      { id: 18574, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18575, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18576, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18577, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18578, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18579, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18580, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18581, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18582, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18583, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18584, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18585, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18586, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18652, name:	"SOUTH INTERNATIONAL FALL"},
      { id: 18691, name:	"UPPER SIOUX INDIAN RESER"},
      { id: 18718, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18719, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18720, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18721, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18722, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18723, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18724, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18725, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18726, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18727, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18728, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18729, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18730, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18731, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18732, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18733, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18734, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18786, name:	"FOND DU LAC INDIAN RESER"},
      { id: 18802, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18803, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18804, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18805, name:	"LEECH LAKE INDIAN RESERV"},
      { id: 18806, name:	"LOWER SIOUX INDIAN RESER"},
      { id: 18821, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18822, name:	"RED LAKE BAND INDIAN RES"},
      { id: 18849, name:	"WHITE EARTH INDIAN RESER"},
      { id: 18934, name:	"MILLE LACS INDIAN RESERV"},
      { id: 19001, name:	"SHAKOPEE MDEWAKANTON SIO"},
      { id: 22942, name:	"SOUTH HACKENSACK TOWNSHI"},
      { id: 23467, name:	"PARSIPPANY-TROY HILLS TO"},
      { id: 23605, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23619, name:	"LAGUNA PUEBLO INDIAN RES"},
      { id: 23620, name:	"LAGUNA PUEBLO INDIAN RES"},
      { id: 23623, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23664, name:	"LAGUNA PUEBLO INDIAN RES"},
      { id: 23668, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23669, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23673, name:	"SANDIA PUEBLO INDIAN RES"},
      { id: 23695, name:	"LAGUNA PUEBLO INDIAN RES"},
      { id: 23699, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23700, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23701, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23705, name:	"SANDIA PUEBLO INDIAN RES"},
      { id: 23798, name:	"ESPANOLA OHKAY OWINGEH P"},
      { id: 23799, name:	"ESPANOLA SANTA CLARA GRA"},
      { id: 23800, name:	"ESPANOLA SANTA CLARA GRA"},
      { id: 23863, name:	"LOS RANCHOS DE ALBUQUERQ"},
      { id: 23864, name:	"LOS RANCHOS DE ALBUQUERQ"},
      { id: 23885, name:	"NAMBE PUEBLO INDIAN RESE"},
      { id: 23887, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 23999, name:	"TRUTH OR CONSEQUENCES AI"},
      { id: 24017, name:	"WHITE SANDS MISSILE RANG"},
      { id: 24064, name:	"LOVINGTON INDUSTRIAL PAR"},
      { id: 28458, name:	"MONCLOVA-MAUMEE-TOLEDO J"},
      { id: 34054, name:	"CATAWBA INDIAN RESERVATI"},
      { id: 34561, name:	"OGLALA INDIAN RESERVATIO"},
      { id: 34565, name:	"ROSEBUD INDIAN RESERVATI"},
      { id: 34581, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34607, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34670, name:	"ROSEBUD INDIAN RESERVATI"},
      { id: 34703, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34704, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34744, name:	"CHEYENNE RIVER INDIAN RE"},
      { id: 34745, name:	"CHEYENNE RIVER INDIAN RE"},
      { id: 34759, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34760, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34761, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34762, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34763, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34764, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34765, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34766, name:	"CROW CREEK INDIAN RESERV"},
      { id: 34782, name:	"FLANDREAU SANTEE INDIAN"},
      { id: 34866, name:	"OGLALA INDIAN RESERVATIO"},
      { id: 34867, name:	"OGLALA INDIAN RESERVATIO"},
      { id: 34899, name:	"ROSEBUD INDIAN RESERVATI"},
      { id: 34900, name:	"ROSEBUD INDIAN RESERVATI"},
      { id: 34901, name:	"ROSEBUD INDIAN RESERVATI"},
      { id: 34978, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34979, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34980, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34981, name:	"YANKTON INDIAN RESERVATI"},
      { id: 34982, name:	"YANKTON INDIAN RESERVATI"},
      { id: 35013, name:	"OGLALA INDIAN RESERVATIO"},
      { id: 36129, name:	"VILLAGE OF TIMBERCREEK C"},
      { id: 38494, name:	"EMIGRATION CANYON TOWNSH"},
      { id: 38769, name:	"NAVAJO INDIAN RESERVATIO"},
      { id: 39148, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39289, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39290, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39291, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39292, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39293, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39294, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39295, name:	"DULLES INTERNATIONAL AIR"},
      { id: 39296, name:	"DULLES INTL FORWARDING F"},
      { id: 39348, name:	"KING AND QUEEN COURT HOU"},
      { id: 40252, name:	"YAKAMA INDIAN RESERVATIO"},
      { id: 40688, name:	"QUILEUTE INDIAN RESERVAT"},
      { id: 40689, name:	"QUILLAYUTE INDIAN RESERV"},
      { id: 40803, name:	"SWINOMISH INDIAN RESERVA"},
      { id: 40876, name:	"YAKAMA INDIAN RESERVATIO"},
      { id: 40877, name:	"YAKAMA INDIAN RESERVATIO"},
      { id: 16469, name:	"HANSCOM AIR FORCE BASE"},
      { id: 12382, name:	"BROOKRIDGE"},
      { id: 12383, name:	"BROOKRIDGE"},
      { id: 12384, name:	"BROOKRIDGE"},
      { id: 12587, name:	"INDIAN CREEK"},
      { id: 12895, name:	"SPRINT CORPORATION"},
      { id: 12585, name:	"INDIAN CREEK"},
      { id: 12586, name:	"INDIAN CREEK"},
      { id: 4171, name:	"CONIFER"},
      { id: 15351, name:	"GUNPOWDER"},
      { id: 16314, name:	"BASS RIVER"},
      { id: 15778, name:	"ALLENDALE"},
      { id: 15872, name:	"DIVISION STREET"},
      { id: 15961, name:	"LUNDS CORNER"},
      { id: 16305, name:	"NORTH"},
      { id: 16340, name:	"MARTHA'S VINEYARD"},
      { id: 15810, name:	"BEVERLY FARMS"},
      { id: 15810, name:	"BEVERLY FARMS"},
      { id: 16148, name:	"WARD HILL"},
      { id: 15884, name:	"EAST LYNN"},
      { id: 16167, name:	"WEST LYNN"},
      { id: 16048, name:	"PLUM ISLAND"},
      { id: 16144, name:	"WALLIS STREET"},
      { id: 16247, name:	"LAURENCE G HANSCOM FIELD"}
    ]
  end
  
end
