---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/email_templates/get_details":
    get:
      summary: fetch email template
      tags:
      - Email Templates
      parameters:
      - name: id
        in: query
        schema:
          type: object
          properties:
            id:
              type: integer
          required:
          - id
      responses:
        '200':
          description: get details
  "/email_templates/{id}":
    put:
      summary: update email template
      tags:
      - Update Email Templates
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: template
        in: query
        schema:
          type: object
          properties:
            enable_template:
              type: boolean
            template:
              type: string
      responses:
        '200':
          description: name found
  "/lease-application-gps-units?id={id}":
    get:
      summary: Returns GPS unit by ID
      tags:
      - GPS
      parameters:
      - name: id
        in: query
        schema:
          type: object
          properties:
            id:
              type: integer
          required:
          - id
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: 3
                lease_application_id: 39932
                gps_serial_number: a1234b56
                active: false
                created_by_admin_id: 132
                updated_by_admin_id: 3
                created_at: '2021-06-30T19:41:31.539-04:00'
                updated_at: '2021-07-01T15:59:30.307-04:00'
              schema:
                type: object
                properties:
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      lease_application_id:
                        type: integer
                      gps_serial_number:
                        type: string
                      active:
                        type: boolean
                      created_by_admin_id:
                        type: integer
                      updated_by_admin_id:
                        type: integer
                      created_at:
                        type: datetime
                      updated_at:
                        type: datetime
    put:
      summary: Update GPS unit
      tags:
      - GPS
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: query
        schema:
          type: object
          properties:
            lease_application_id:
              type: integer
            gps_serial_number:
              type: string
            active:
              type: boolean
            created_by_admin_id:
              type: integer
            updated_by_admin_id:
              type: integer
      responses:
        '200':
          description: GPS unit has been successfully updated.
    post:
      summary: Create a Lease GPS unit
      tags:
      - GPS
      parameters:
      - name: gps_unit
        in: query
        schema:
          type: object
          properties:
            lease_application_id:
              type: integer
            gps_serial_number:
              type: string
            active:
              type: boolean
            created_by_admin_id:
              type: integer
            updated_by_admin_id:
              type: integer
          required:
          - lease_application_id
          - gps_serial_number
          - active
      responses:
        '201':
          description: Successfully created
    delete:
      summary: Delete GPS unit
      tags:
      - GPS
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: GPS unit has been successfully deleted.
  "/lease-application-stipulations":
    post:
      summary: create a Lease Stipulation
      tags:
      - Stipulation
      parameters:
      - name: application_identifier
        in: path
        required: true
        schema:
          type: string
      - name: stipulation
        in: query
        schema:
          type: object
          properties:
            stipulation_id:
              type: integer
            status:
              type: string
            notes:
              type: string
          required:
          - stipulation_id
          - status
          - notes
      responses:
        '201':
          description: Stipulation created
  "/mail-carriers":
    get:
      summary: fetch Mail Carriers
      tags:
      - Mail Carrier
      responses:
        '200':
          description: get Mail Carriers
  "/mail-carriers/update-active-mail-carriers":
    put:
      summary: update Active
      tags:
      - Mail Carrier
      parameters:
      - name: mail_carrier
        in: query
        schema:
          type: object
          properties:
            id:
              type: integer
            active:
              type: boolean
          required:
          - id
          - active
      responses:
        '200':
          description: Active updated
  "/mail-carriers/update-description":
    put:
      summary: update Description
      tags:
      - Mail Carrier
      parameters:
      - name: mail_carrier
        in: query
        schema:
          type: object
          properties:
            id:
              type: integer
            description:
              type: string
          required:
          - id
          - description
      responses:
        '200':
          description: Description updated
  "/model-groups?make_id={make_id}":
    get:
      summary: Returns list of model groups by make ID
      tags:
      - Makes
      parameters:
      - name: make_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                message: Model Groups List Data
                model_groups:
                - id: 3
                  name: Sportster
                  sort_index: 1
                - id: 5
                  name: dyna
                  sort_index: 2
              schema:
                type: object
                properties:
                  message:
                    type: string
                  model_groups:
                    type: array
                    items:
                      type: object
                      properties:
                        make_id:
                          type: integer
                        name:
                          type: string
                        sort_index:
                          type: integer
                required:
                - make_id
        '404':
          description: Not found
  "/model-groups/sort-order":
    put:
      summary: Updates the sort order used by the UI
      tags:
      - Model Groups
      parameters: []
      responses:
        '200':
          description: Sort order updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                modelGroups:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      sortIndex:
                        type: integer
        required: true
  "/security-roles/can-see-welcome-call-dashboard":
    get:
      summary: fetch Security Roles to see welcome call dashbaord
      tags:
      - Security Roles
      responses:
        '200':
          description: get Security Roles
servers:
- url: "{production}"
  description: Production
  variables:
    production:
      default: https://admin.speedleasing.com/api/v1
- url: "{staging}"
  description: Staging
  variables:
    staging:
      default: https://admin.staging.speedleasing.com/api/v1
- url: "{local}"
  description: Local development
  variables:
    local:
      default: http://localhost:3000/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
- bearerAuth: []
